version: "3.9"

networks:
  transferences-network:

services:
  transference:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - transferences-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/transferencesdb
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672

  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: transferencesdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - transferences-network

  rabbitmq:
    image: rabbitmq:3.12-management
    restart: always
    ports:
      - "5672:5672"    # broker
      - "15672:15672"  # dashboard
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - transferences-network

volumes:
  postgres_data:
  rabbitmq_data:
