spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: admin
    password: admin
    connection-timeout: 30000
    template:
      retry:
        enabled: true
        max-attempts: 5
        initial-interval: 5s
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 5000
          max-attempts: 3
          max-interval: 60000
          multiplier: 2.0

  datasource:
    url: jdbc:postgresql://localhost:5432/transferencesdb
    username: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

resilience4j:
  retry:
    instances:
      authorizationRetry:
        maxAttempts: 3
        waitDuration: 2s

  timelimiter:
    instances:
      authorizationTimeLimiter:
        timeoutDuration: 3s
