
logging:
  level:
    org.flywaydb: DEBUG
spring:
  flyway:
    schemas: public
    enabled: true
    locations: classpath:db/migration

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    connection-timeout: 30000
    template:
      retry:
        enabled: true
        max-attempts: 5
        initial-interval: 5s
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 5000
          max-attempts: 3
          max-interval: 60000
          multiplier: 2.0

  datasource:
    url: jdbc:postgresql://localhost:5432/transferencesdb
    username: admin
    password: admin

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

resilience4j:
  retry:
    instances:
      authorizationRetry:
        maxAttempts: 3
        waitDuration: 2s
      notificationRetry:
        maxAttempts: 3
        waitDuration: 2s
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
        maxWaitDuration: 10s

  timelimiter:
    instances:
      authorizationTimeLimiter:
        timeoutDuration: 3s
      notificationTimeLimiter:
        timeoutDuration: 3s
